apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod
namePrefix: prod-

bases:
  - ../../base

resources:
  - ing.yaml

patchesStrategicMerge:
- patch-rs.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: timber-backend
  patch: |-
    - op: remove
      path: /metadata/labels/owner
    - op: add
      path: /metadata/labels/food
      value: krumpli